[[ISSUERS]]
address = "rfUhMQYijKvStp96CUxDNp8ukYJAebNrJ1"
name = "MoonFlex"

[[TOKENS]]
issuer = "rfUhMQYijKvStp96CUxDNp8ukYJAebNrJ1"
currency = "MFX"
name = "MoonFlex"
desc = "Interstellar token on the XRP Ledger."
icon = "https://moonflex.xyz/moonflex-token-256.png"

[[TOKENS.WEBLINKS]]
url = "https://x.com/moonflextoken"
type = "socialmedia"
title = "Twitter"
